namespace Kiyaslasana.EL.Entities;

public sealed class Telefon
{
    public int Id { get; set; }
    public string? ModelAdi { get; set; }
    public string? Marka { get; set; }
    public string? ResimUrl { get; set; }
    public string? NetworkTeknolojisi { get; set; }
    public string? DuyurulmaTarihi { get; set; }
    public string? DuyurulmaTarihiTr { get; set; }
    public string? PiyasayaCikisDurumu { get; set; }
    public string? PiyasayaCikisDurumuTr { get; set; }
    public string? Boyutlar { get; set; }
    public string? Agirlik { get; set; }
    public string? GovdeMalzemesi { get; set; }
    public string? GovdeMalzemesiTr { get; set; }
    public string? Sim { get; set; }
    public string? SimTr { get; set; }
    public string? GovdeDiger { get; set; }
    public string? GovdeDigerTr { get; set; }
    public string? EkranTipi { get; set; }
    public string? EkranBoyutu { get; set; }
    public string? EkranBoyutuTr { get; set; }
    public string? EkranCozunurlugu { get; set; }
    public string? EkranCozunurluguTr { get; set; }
    public string? EkranKorumasi { get; set; }
    public string? EkranDigerOzellikler { get; set; }
    public string? IsletimSistemi { get; set; }
    public string? IsletimSistemiTr { get; set; }
    public string? YongaSeti { get; set; }
    public string? Cpu { get; set; }
    public string? Gpu { get; set; }
    public string? GpuTr { get; set; }
    public string? HafizaKartiYuvasi { get; set; }
    public string? HafizaKartiYuvasiTr { get; set; }
    public string? DahiliHafiza { get; set; }
    public string? AnaKameraModulleri { get; set; }
    public string? AnaKameraModulleriTr { get; set; }
    public string? AnaKameraOzellikleri { get; set; }
    public string? AnaKameraOzellikleriTr { get; set; }
    public string? AnaKameraVideo { get; set; }
    public string? AnaKameraVideoTr { get; set; }
    public string? OnKameraModulleri { get; set; }
    public string? OnKameraModulleriTr { get; set; }
    public string? OnKameraOzellikleri { get; set; }
    public string? OnKameraOzellikleriTr { get; set; }
    public string? OnKameraVideo { get; set; }
    public string? OnKameraVideoTr { get; set; }
    public string? Hoparlor { get; set; }
    public string? HoparlorTr { get; set; }
    public string? Ses35MmJack { get; set; }
    public string? Ses35MmJackTr { get; set; }
    public string? SesDigerOzellikler { get; set; }
    public string? Wlan { get; set; }
    public string? Bluetooth { get; set; }
    public string? KonumlandirmaGps { get; set; }
    public string? Nfc { get; set; }
    public string? NfcTr { get; set; }
    public string? KizilotesiPortu { get; set; }
    public string? Radyo { get; set; }
    public string? RadyoTr { get; set; }
    public string? Usb { get; set; }
    public string? Sensorler { get; set; }
    public string? SensorlerTr { get; set; }
    public string? BataryaTipi { get; set; }
    public string? SarjOzellikleri { get; set; }
    public string? SarjOzellikleriTr { get; set; }
    public string? BataryaDiger { get; set; }
    public string? Renkler { get; set; }
    public string? RenklerTr { get; set; }
    public string? ModelVaryantlari { get; set; }
    public string? SarAb { get; set; }
    public string? SarAbTr { get; set; }
    public string? SarAbd { get; set; }
    public string? SarAbdTr { get; set; }
    public string? Fiyat { get; set; }
    public string? PerformansTestleri { get; set; }
    public string? TestlerEkran { get; set; }
    public string? TestlerEkranTr { get; set; }
    public string? TestlerKameraLink { get; set; }
    public string? TestlerHoparlorLink { get; set; }
    public string? TestlerBataryaOmruPuan { get; set; }
    public string? TestlerBataryaOmruPuanTr { get; set; }
    public string? TestlerBataryaOmruDetayLink { get; set; }
    public string? TestlerAktifKullanimSkoru { get; set; }
    public string? TestlerAktifKullanimSkoruTr { get; set; }
    public string? ReviewDurumu { get; set; }
    public string? ReviewIcerigi { get; set; }
    public string? ReviewIcerigiTurkce { get; set; }
    public string? Url { get; set; }
    public DateTimeOffset? SonGuncelleme { get; set; }
    public DateTimeOffset? KayitTarihi { get; set; }
    public string? Slug { get; set; }
}
