// <auto-generated />
using System;
using Kiyaslasana.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiyaslasana.DAL.Migrations
{
    [DbContext(typeof(KiyaslasanaDbContext))]
    [Migration("20260216000100_AddBlogPosts")]
    partial class AddBlogPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kiyaslasana.EL.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Kiyaslasana.EL.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_raw");

                    b.Property<string>("ContentSanitized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_sanitized");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("excerpt");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("meta_title");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blog_posts");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_blog_posts_published_at");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_posts_slug");

                    b.ToTable("blog_posts", (string)null);
                });

            modelBuilder.Entity("Kiyaslasana.EL.Entities.Telefon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agirlik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agirlik");

                    b.Property<string>("AnaKameraModulleri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ana_kamera_modulleri");

                    b.Property<string>("AnaKameraModulleriTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ana_kamera_modulleri_tr");

                    b.Property<string>("AnaKameraOzellikleri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ana_kamera_ozellikleri");

                    b.Property<string>("AnaKameraOzellikleriTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ana_kamera_ozellikleri_tr");

                    b.Property<string>("AnaKameraVideo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ana_kamera_video");

                    b.Property<string>("AnaKameraVideoTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ana_kamera_video_tr");

                    b.Property<string>("BataryaDiger")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("batarya_diger");

                    b.Property<string>("BataryaTipi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("batarya_tipi");

                    b.Property<string>("Bluetooth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bluetooth");

                    b.Property<string>("Boyutlar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("boyutlar");

                    b.Property<string>("Cpu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpu");

                    b.Property<string>("DahiliHafiza")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dahili_hafiza");

                    b.Property<string>("DuyurulmaTarihi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duyurulma_tarihi");

                    b.Property<string>("DuyurulmaTarihiTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duyurulma_tarihi_tr");

                    b.Property<string>("EkranBoyutu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_boyutu");

                    b.Property<string>("EkranBoyutuTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_boyutu_tr");

                    b.Property<string>("EkranCozunurlugu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_cozunurlugu");

                    b.Property<string>("EkranCozunurluguTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_cozunurlugu_tr");

                    b.Property<string>("EkranDigerOzellikler")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_diger_ozellikler");

                    b.Property<string>("EkranKorumasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_korumasi");

                    b.Property<string>("EkranTipi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ekran_tipi");

                    b.Property<string>("Fiyat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fiyat");

                    b.Property<string>("GovdeDiger")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("govde_diger");

                    b.Property<string>("GovdeDigerTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("govde_diger_tr");

                    b.Property<string>("GovdeMalzemesi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("govde_malzemesi");

                    b.Property<string>("GovdeMalzemesiTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("govde_malzemesi_tr");

                    b.Property<string>("Gpu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gpu");

                    b.Property<string>("GpuTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gpu_tr");

                    b.Property<string>("HafizaKartiYuvasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hafiza_karti_yuvasi");

                    b.Property<string>("HafizaKartiYuvasiTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hafiza_karti_yuvasi_tr");

                    b.Property<string>("Hoparlor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hoparlor");

                    b.Property<string>("HoparlorTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hoparlor_tr");

                    b.Property<string>("IsletimSistemi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isletim_sistemi");

                    b.Property<string>("IsletimSistemiTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isletim_sistemi_tr");

                    b.Property<DateTimeOffset?>("KayitTarihi")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("kayit_tarihi");

                    b.Property<string>("KizilotesiPortu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kizilotesi_portu");

                    b.Property<string>("KonumlandirmaGps")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("konumlandirma_gps");

                    b.Property<string>("Marka")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("marka");

                    b.Property<string>("ModelAdi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model_adi");

                    b.Property<string>("ModelVaryantlari")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model_varyantlari");

                    b.Property<string>("NetworkTeknolojisi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("network_teknolojisi");

                    b.Property<string>("Nfc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nfc");

                    b.Property<string>("NfcTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nfc_tr");

                    b.Property<string>("OnKameraModulleri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("on_kamera_modulleri");

                    b.Property<string>("OnKameraModulleriTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("on_kamera_modulleri_tr");

                    b.Property<string>("OnKameraOzellikleri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("on_kamera_ozellikleri");

                    b.Property<string>("OnKameraOzellikleriTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("on_kamera_ozellikleri_tr");

                    b.Property<string>("OnKameraVideo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("on_kamera_video");

                    b.Property<string>("OnKameraVideoTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("on_kamera_video_tr");

                    b.Property<string>("PerformansTestleri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("performans_testleri");

                    b.Property<string>("PiyasayaCikisDurumu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("piyasaya_cikis_durumu");

                    b.Property<string>("PiyasayaCikisDurumuTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("piyasaya_cikis_durumu_tr");

                    b.Property<string>("Radyo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("radyo");

                    b.Property<string>("RadyoTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("radyo_tr");

                    b.Property<string>("Renkler")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renkler");

                    b.Property<string>("RenklerTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("renkler_tr");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resim_url");

                    b.Property<string>("ReviewDurumu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_durumu");

                    b.Property<string>("ReviewIcerigi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_icerigi");

                    b.Property<string>("ReviewIcerigiTurkce")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_icerigi_turkce");

                    b.Property<string>("SarAb")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sar_ab");

                    b.Property<string>("SarAbTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sar_ab_tr");

                    b.Property<string>("SarAbd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sar_abd");

                    b.Property<string>("SarAbdTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sar_abd_tr");

                    b.Property<string>("SarjOzellikleri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sarj_ozellikleri");

                    b.Property<string>("SarjOzellikleriTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sarj_ozellikleri_tr");

                    b.Property<string>("Sensorler")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sensorler");

                    b.Property<string>("SensorlerTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sensorler_tr");

                    b.Property<string>("Ses35MmJack")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ses_3_5mm_jack");

                    b.Property<string>("Ses35MmJackTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ses_3_5mm_jack_tr");

                    b.Property<string>("SesDigerOzellikler")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ses_diger_ozellikler");

                    b.Property<string>("Sim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sim");

                    b.Property<string>("SimTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sim_tr");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("SonGuncelleme")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("son_guncelleme");

                    b.Property<string>("TestlerAktifKullanimSkoru")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_aktif_kullanim_skoru");

                    b.Property<string>("TestlerAktifKullanimSkoruTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_aktif_kullanim_skoru_tr");

                    b.Property<string>("TestlerBataryaOmruDetayLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_batarya_omru_detay_link");

                    b.Property<string>("TestlerBataryaOmruPuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_batarya_omru_puan");

                    b.Property<string>("TestlerBataryaOmruPuanTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_batarya_omru_puan_tr");

                    b.Property<string>("TestlerEkran")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_ekran");

                    b.Property<string>("TestlerEkranTr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_ekran_tr");

                    b.Property<string>("TestlerHoparlorLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_hoparlor_link");

                    b.Property<string>("TestlerKameraLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testler_kamera_link");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<string>("Usb")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usb");

                    b.Property<string>("Wlan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wlan");

                    b.Property<string>("YongaSeti")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yonga_seti");

                    b.HasKey("Id")
                        .HasName("pk_telefonlar");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_telefonlar_slug")
                        .HasFilter("[slug] IS NOT NULL");

                    b.HasIndex("Marka", "Slug")
                        .HasDatabaseName("ix_telefonlar_marka_slug");

                    b.ToTable("telefonlar", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Kiyaslasana.EL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Kiyaslasana.EL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Kiyaslasana.EL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Kiyaslasana.EL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
